### ISSUE TITLE
renaming Get-SQLInstance

### ISSUE THREAD

**Issue by chipitsine** [proxb/PowerShell_Scripts#7]
there's another Get-SQLInstance (which is not very usable because of mandatory "Credential")

https://technet.microsoft.com/en-us/library/mt759805.aspx

please, rename Get-SQLInstance commandlet

(we agreed on that in email conversation, I open an issue to keep it in mind)

**Comment by proxb** [comment]
I'll probably rename it to Get-PSSQLInstance to avoid excessive characters

**Comment by chipitsine** [comment]
It would be nice to include "database engine" in some way. There will be also commandlets to enumerate other sql server components, i.e. reporting, analysis, agent,...
